name: TicBuddy
options:
  bundleIdPrefix: com.ticbuddy
  deploymentTarget:
    iOS: "17.0"
  defaultConfig: Debug

settings:
  SWIFT_VERSION: "6.0"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  DEVELOPMENT_TEAM: ""  # Add your Apple Developer Team ID here

configs:
  Debug: debug
  Release: release

targets:
  TicBuddy:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TicBuddy
        excludes:
          - "**/.DS_Store"
    resources:
      - path: TicBuddy/Assets.xcassets
      - path: TicBuddy/Preview Content
    info:
      path: TicBuddy/Info.plist
      properties:
        CFBundleName: TicBuddy
        CFBundleDisplayName: TicBuddy
        CFBundleIdentifier: com.ticbuddy.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSPrivacyAccessedAPITypes: []
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.ticbuddy.app
      INFOPLIST_FILE: TicBuddy/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      DEBUG_INFORMATION_FORMAT: dwarf
