// TicBuddy — DailyInstructionEngine.swift
// Daily caregiver practice instructions engine (tb-mvp2-005).
//
// Provides session-stage-specific, clinically accurate CBIT practice
// instructions for the caregiver's 10–20 minute daily practice window.
//
// CLINICAL BASIS:
//   Instructions follow the CBIT protocol (Woods et al., 2008):
//   Sessions 1–5 weekly, sessions 6–7 biweekly, session 8 monthly.
//   Each stage has a specific focus per the manual:
//     Session 1 — psychoeducation + tic inventory + awareness training
//     Session 2 — introduce first competing response (CR)
//     Session 3 — troubleshoot CR + relaxation exercises
//     Session 4 — consolidate + introduce CR for second tic
//     Session 5 — generalization + build independence
//     Session 6–7 — biweekly maintenance + brief check-in
//     Session 8 — relapse prevention + graduation plan
//
// PERSONALIZATION:
//   When a target tic + competing response are provided, the engine
//   substitutes the child-specific tic name and CR into the steps,
//   so instructions are never generic boilerplate.
//
// USAGE:
//   let instruction = DailyInstructionEngine.instruction(
//       for: child.sessionStage,
//       targetTic: child.currentTargetTic,
//       practiceCalendar: sharedData.practiceCalendar,
//       childName: child.displayName
//   )

import Foundation

// MARK: - Daily Instruction Model

/// A structured daily practice instruction for the caregiver.
/// Generated by DailyInstructionEngine based on the child's CBITSessionStage.
struct DailyInstruction: Equatable {
    /// Short title for the instruction card header, e.g. "Today: Awareness"
    var title: String
    /// 1-sentence core focus, e.g. "Catch urges before the tic fires."
    var focus: String
    /// Ordered practice steps — shown as a numbered list to the caregiver.
    /// Personalized with the child's name and target tic when available.
    var steps: [String]
    /// A single coaching tip from the CBIT therapist's perspective.
    var coachingTip: String
    /// Estimated practice duration in minutes
    var estimatedMinutes: Int
    /// Visual emoji accent for the card
    var emoji: String
    /// Whether this is a full-session day (weekly/biweekly) vs a daily drill day
    var isFullSessionDay: Bool
}

// MARK: - Daily Instruction Engine

enum DailyInstructionEngine {

    // MARK: - Public API

    /// Returns the appropriate daily practice instruction for a child.
    ///
    /// - Parameters:
    ///   - stage: The child's current CBITSessionStage
    ///   - targetTic: Their currently active target tic (nil = no tic assigned yet)
    ///   - practiceCalendar: The shared practice calendar to compute weekly cadence
    ///   - childName: Display name for personalized copy
    /// - Returns: A `DailyInstruction` to show in the caregiver dashboard
    static func instruction(
        for stage: CBITSessionStage,
        targetTic: TicHierarchyEntry?,
        practiceCalendar: [String: PracticeStatus],
        childName: String,
        isSelfUser: Bool = false   // tb-mvp2-034: self-users get first-person framing
    ) -> DailyInstruction {

        // tb-mvp2-034: name = "you" for self-users; namePos = possessive ("your" vs "Alex's")
        let name    = isSelfUser ? "you"  : (childName.isEmpty ? "your child" : childName)
        let namePos = isSelfUser ? "your" : (childName.isEmpty ? "your child's" : "\(childName)'s")
        let ticName = targetTic?.ticName ?? "tic"
        let cr = targetTic?.competingResponse ?? ""
        let practicesThisWeek = weeklyPracticeCount(from: practiceCalendar)
        let isFullSessionDay = practicesThisWeek == 0  // First practice of the week = full session

        switch stage {

        // ─── Session 1: Foundation / Awareness ──────────────────────────────
        case .session1:
            // tb-mvp2-039: Session 1 = awareness training ONLY. No competing response introduction.
            // Homework = catch-counting. Age-appropriate urge names for little kids.
            return DailyInstruction(
                title: "Today: Awareness Building 👀",
                focus: isSelfUser
                    ? "Discover the body signal (premonitory urge) that fires before each tic."
                    : "Help \(name) discover the body signal (premonitory urge) that fires before each tic.",
                steps: isFullSessionDay
                    ? [
                        "Find a calm 15–20 min with no distractions.",
                        "Learn the premonitory urge in plain terms: 'The Tingle', 'Your Body's Secret Warning', or 'The Uh-Oh Feeling' — it's the feeling right before the tic fires.",
                        "Frame it as a superpower: \"Every time you feel that signal before the tic, that's a CATCH — and catches are your superpower.\"",
                        "Spend 5 min listing \(namePos) tics — don't judge, just name them.",
                        "Pick ONE tic to focus on this week (most frequent or most noticeable).",
                        "Session 1 homework: count catches each day and log in TicBuddy.",
                        "DO NOT introduce a competing response yet — that's Session 2. This week is pure awareness."
                      ]
                    : [
                        "Quick daily drill — 5 min max.",
                        "Check in: \"Did you feel the Tingle / warning feeling before any tics today? How many catches?\"",
                        "If yes: celebrate — \"That IS your superpower! 💪\"",
                        "If no: that's completely normal — awareness builds over days. \"Keep your detective eyes open!\"",
                        "Log \(namePos) catch count in TicBuddy."
                      ],
                coachingTip: isFullSessionDay
                    ? "Session 1 = noticing ONLY. No competing responses yet — not even as a preview. Introducing them too early derails awareness training. The catch-count homework is the whole point."
                    : isSelfUser
                        ? "Keep daily drills short and positive. When you wonder 'what do I do when I feel the tingle?' — for now, just notice it and count it. You'll learn the next move in Session 2."
                        : "Keep daily drills short and positive. If \(name) asks 'what do I do when I feel the tingle?', say: 'For now, just notice it and count it — we learn the next move next week!'",
                estimatedMinutes: isFullSessionDay ? 20 : 5,
                emoji: "🔍",
                isFullSessionDay: isFullSessionDay
            )

        // ─── Session 2: First Competing Response ───────────────────────────
        case .session2:
            let crText = cr.isEmpty
                ? "the competing response your therapist or TicBuddy suggested"
                : cr
            return DailyInstruction(
                title: "Today: Practice the CR 💪",
                focus: "Build fluency with \(namePos) first competing response for \(ticName).",
                steps: isFullSessionDay
                    ? [
                        isSelfUser ? "Set aside 15 min with no distractions." : "Sit together for 15 min.",
                        "Review the tic: \"\(ticName)\" — can you feel the urge before it fires?",
                        "Introduce or review the competing response: \(crText).",
                        "Practice the CR: 5 repetitions back-to-back, no tic needed.",
                        "Then practice IN RESPONSE to the urge: when you feel the urge, immediately start the CR and hold for ~60 sec.",
                        "Debrief: \"Did it help? How strong was the urge before vs after?\""
                      ]
                    : [
                        "5 min daily drill.",
                        "Check in: \"Did you use your CR today when you felt the \(ticName) urge?\"",
                        "If yes: celebrate! \"Your brain is literally rewiring right now.\"",
                        "If no: briefly practice the CR — 3 reps.",
                        "Remind yourself: the goal isn't to eliminate — it's to redirect when the urge appears."
                      ],
                coachingTip: isFullSessionDay
                    ? "The CR only works if you start it when you feel the urge — not after the tic fires. Focus on urge detection, not tic suppression."
                    : "Short daily practice between sessions is what locks in the neural pathway change.",
                estimatedMinutes: isFullSessionDay ? 15 : 5,
                emoji: "💪",
                isFullSessionDay: isFullSessionDay
            )

        // ─── Session 3: Troubleshoot + Relaxation ─────────────────────────
        case .session3:
            let crText = cr.isEmpty ? "the competing response" : cr
            return DailyInstruction(
                title: "Today: Troubleshoot & Relax 🛠️",
                focus: "Fix any barriers to the CR + add relaxation as a tic reducer.",
                steps: isFullSessionDay
                    ? [
                        "Ask honestly: \"Is the CR working? When does it fail?\" (e.g., in school, when tired).",
                        "Troubleshoot together: What makes it hard? Adjust the CR if needed.",
                        "Introduce deep diaphragmatic breathing (4-count in, 4-count hold, 6-count out).",
                        "Practice: 3 breathing cycles → then the CR for \(ticName).",
                        "Identify a 'tic-prone situation' this week: when does \(ticName) spike?",
                        "Make a plan: what will you do when it spikes in that situation?"
                      ]
                    : [
                        "Quick daily check-in, 5–7 min.",
                        "Ask: \"How's the \(crText) going? Any hard moments today?\"",
                        "Do 2 rounds of breathing together (4 in, 4 hold, 6 out).",
                        "Ask: \"Did tics feel worse or better today? Any pattern?\"",
                        "Note any new patterns for the next full session."
                      ],
                coachingTip: isFullSessionDay
                    ? "Session 3 is where motivation can dip. Emphasize that troubleshooting IS progress — a CR that needs adjusting is still working."
                    : "Relaxation practice between sessions reduces baseline tic frequency. Even 2 breathing cycles matters.",
                estimatedMinutes: isFullSessionDay ? 20 : 7,
                emoji: "🛠️",
                isFullSessionDay: isFullSessionDay
            )

        // ─── Session 4: Consolidate + Second Tic ──────────────────────────
        case .session4:
            return DailyInstruction(
                title: "Today: Consolidate + Add a Tic 🎯",
                focus: "Strengthen the first CR and begin work on a second tic.",
                steps: isFullSessionDay
                    ? [
                        "Start with \(ticName): quick review of the CR (\(cr.isEmpty ? "current competing response" : cr)). How confident are you? Rate 1–10.",
                        "If confidence is 7+: celebrate and move on. If below 7: do 5 quick reps.",
                        "Introduce the second tic from \(namePos) hierarchy: name it, notice the urge.",
                        "If a CR has been chosen for tic #2, introduce it. Otherwise, brainstorm together.",
                        "Practice tic #2 CR: 3–5 reps, then 1 urge-response cycle.",
                        "End with encouragement: \"You're training two tics now — that's huge.\""
                      ]
                    : [
                        "5 min drill — cover both tics.",
                        "Ask: \"Did you use the CR for \(ticName) today?\"",
                        "Ask: \"Did you notice tic #2 at all today?\"",
                        "Celebrate any use of either CR.",
                        "Quick note: which tic needed more effort today?"
                      ],
                coachingTip: isFullSessionDay
                    ? "Don't advance to tic #2 until tic #1 CR feels automatic (7+/10 confidence). If not there yet, spend this session consolidating tic #1 only."
                    : "Two CRs can feel overwhelming. Keep daily drills focused — one tic per day if needed.",
                estimatedMinutes: isFullSessionDay ? 20 : 5,
                emoji: "🎯",
                isFullSessionDay: isFullSessionDay
            )

        // ─── Session 5: Independence + Generalization ─────────────────────
        case .session5:
            return DailyInstruction(
                title: "Today: Build Independence 🚀",
                focus: isSelfUser
                    ? "Build independence — use your CR without prompts or reminders."
                    : "Help \(name) use the CR independently, without reminders.",
                steps: isFullSessionDay
                    ? [
                        isSelfUser
                            ? "Reflect: \"This week, did you ever use the CR without being prompted or reminded? Celebrate if yes.\""
                            : "Ask: \"This week, did you ever use the CR without me reminding you?\" Celebrate if yes.",
                        isSelfUser
                            ? "Role-play a hard scenario: school, social situations, eating out — practice using the CR in the 'hard' context."
                            : "Role-play a hard scenario: school, sports, eating out — \(name) practices using the CR in the 'hard' context.",
                        "Reflect: \"What gets in the way of using it independently?\" (social fear, forgetting, too tired).",
                        isSelfUser
                            ? "Create a personal cue: a word, gesture, or self-reminder you can use as a prompt."
                            : "Create a personal cue: a word, gesture, or reminder \(name) can use as a self-prompt.",
                        "Practice the cue → urge detection → CR chain end-to-end.",
                        "Transition talk: \"In a few weeks, you'll check in less often — you'll own this.\""
                      ]
                    : [
                        "5 min check-in.",
                        "Ask: \"Did you use the CR on your own today — without me reminding you?\"",
                        "Celebrate independence, even partial.",
                        "If they forgot: no shame — \"What would help you remember tomorrow?\"",
                        "Keep tracking. Independence builds slowly."
                      ],
                coachingTip: isFullSessionDay
                    ? "Your role is shifting from coach to cheerleader. Praise self-initiated CR use far more than prompted use — it's the real goal."
                    : "The transition to independence is gradual. Daily check-ins should get shorter each week as they internalize the skill.",
                estimatedMinutes: isFullSessionDay ? 20 : 5,
                emoji: "🚀",
                isFullSessionDay: isFullSessionDay
            )

        // ─── Session 6: Biweekly Maintenance ──────────────────────────────
        case .session6:
            return DailyInstruction(
                title: "Biweekly Check-In 📋",
                focus: "Quick progress review — tics, CRs, and how things are going in real life.",
                steps: [
                    "This is a maintenance check-in (10–15 min).",
                    "Review: How often have you used \(namePos) CR(s) in the past 2 weeks?",
                    "Check tic intensity: \"On a 1–10 scale, how distressing is \(ticName) now vs when we started?\"",
                    "Any new tics or spikes? Log them without alarm.",
                    "Celebrate wins — even small ones count at this stage.",
                    "No new CRs unless asked — consolidation is the goal."
                ],
                coachingTip: "Maintenance sessions should be light and positive — resist adding new homework. The work has already been done; now it's about staying consistent.",
                estimatedMinutes: 15,
                emoji: "📋",
                isFullSessionDay: true
            )

        // ─── Session 7: Monthly Maintenance ───────────────────────────────
        case .session7:
            return DailyInstruction(
                title: "Monthly Check-In 🌙",
                focus: "Monthly maintenance — celebrate progress and plan ahead.",
                steps: [
                    "This is a monthly maintenance session (15–20 min).",
                    "Reflect: \"What's the biggest change you've noticed in your tics this month?\"",
                    "Rate current tic distress vs Session 1 baseline for each tracked tic.",
                    "Discuss upcoming stressors (school events, holidays, changes) that might spike tics.",
                    "Make a plan: how will you handle a tic spike if it happens?",
                    "Celebrate the journey — you've come a long way."
                ],
                coachingTip: "Monthly sessions are about long-term maintenance, not improvement. Expect some fluctuation — tics wax and wane. Consistency of the CR habit matters more than daily tic counts.",
                estimatedMinutes: 20,
                emoji: "🌙",
                isFullSessionDay: true
            )

        // ─── Session 8: Graduation ─────────────────────────────────────────
        case .session8:
            return DailyInstruction(
                title: "Final Session 🏆",
                focus: "Graduation: celebrate the journey and build a relapse prevention plan.",
                steps: [
                    "Celebrate intentionally — this is a milestone worth marking! 🎉",
                    "Look back: review Session 1 tic inventory. What's improved? Name it specifically.",
                    "Build the relapse prevention plan: \"If tics spike again, here's what we'll do...\"",
                    "Identify early warning signs that suggest a tic is returning or worsening.",
                    "Agree on a response plan: brief daily practice, return to CBIT if needed.",
                    "Close with intention: you now have tools you'll carry for life."
                ],
                coachingTip: "Session 8 is about empowerment, not graduation from tics. Tourette's is a lifelong condition; the tools you've built are lifelong too. Celebrate the toolkit, not a 'cure'.",
                estimatedMinutes: 20,
                emoji: "🏆",
                isFullSessionDay: true
            )
        }
    }

    // MARK: - Private Helpers

    /// Counts how many practices were logged in the current ISO week
    private static func weeklyPracticeCount(from calendar: [String: PracticeStatus]) -> Int {
        let formatter = ISO8601DateFormatter()
        let weekStart = Calendar.current.startOfWeek(for: Date())
        return calendar.keys.filter { key in
            guard let date = formatter.date(from: key) else { return false }
            return date >= weekStart && date <= Date()
        }.count
    }
}

// MARK: - Calendar Extension

private extension Calendar {
    /// Returns midnight on the most recent Monday (start of the current ISO week)
    func startOfWeek(for date: Date) -> Date {
        var components = dateComponents([.yearForWeekOfYear, .weekOfYear], from: date)
        components.weekday = 2  // Monday
        return self.date(from: components) ?? date
    }
}
